services:
  - type: web
    name: ers-frontend
    runtime: node
    buildCommand: npm install
    startCommand: npm run web
    envVars:
      - key: NODE_ENV
        value: production
      - key: //localhost:4000
        value: https://ers-server.onrender.com
    plan: free